# Generated by Django 4.2.20 on 2025-04-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0011_auto_20200730_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='agreement',
            field=models.FileField(blank=True, help_text='Attach sustaining member agreement', upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='approved',
            field=models.BooleanField(default=False, help_text='Whether this sustaining member has been approved for use by the project owner.'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Invoice number for the sustaining member.', max_length=255, null=True, verbose_name='Sustaining membership invoice number'),
        ),
        migrations.AlterField(
            model_name='sponsorshiplevel',
            name='approved',
            field=models.BooleanField(default=False, help_text='Whether this sustaining membership level has been approved for use by the project owner.'),
        ),
        migrations.AlterField(
            model_name='sponsorshiplevel',
            name='currency',
            field=models.CharField(help_text='The currency which associated with this sustaining membership level.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sponsorshiplevel',
            name='logo',
            field=models.ImageField(help_text='An image of sustaining membership level logo e.g. a bronze medal.Most browsers support dragging the image directly on to the "Choose File" button above.', upload_to='images/projects'),
        ),
        migrations.AlterField(
            model_name='sponsorshiplevel',
            name='name',
            field=models.CharField(help_text='Name of sustaining membership level. e.g. Gold, Bronze, etc', max_length=255),
        ),
        migrations.AlterField(
            model_name='sponsorshiplevel',
            name='value',
            field=models.IntegerField(help_text='Amount of money associated with this sustaining membership level.'),
        ),
    ]
