# Generated by Django 4.2.20 on 2025-07-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changes", "0013_sponsor_receive_news_sponsor_tech_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorshiplevel",
            name="id",
            field=models.AutoField(
                help_text="Unique ID for this sustaining membership level.",
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsorshiplevel",
            constraint=models.UniqueConstraint(
                fields=("id",), name="unique_sponsorshiplevel_id"
            ),
        ),
    ]
