# Generated by Django 4.2.20 on 2025-07-02 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('changes', '0014_alter_sponsorshiplevel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('email_type', models.CharField(choices=[('admin', 'Admin Email Only'), ('tech', 'Tech Email Only'), ('both', 'Both Admin and Tech Emails')], default='both', help_text='Select which email addresses to send to for each sponsor', max_length=5)),
                ('cc', models.TextField(blank=True, help_text='Comma separated list of CC emails')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
                ('sponsor_levels', models.ManyToManyField(help_text='Select sponsor levels to receive this email', related_name='emails', to='changes.sponsorshiplevel')),
            ],
            options={
                'verbose_name': 'Sponsor Email',
                'verbose_name_plural': 'Sponsor Emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
