# Generated by Django 4.2.19 on 2025-02-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0025_alter_attendee_surname'),
        ('certification', '0025_alter_historicalcertifyingorganisation_options_and_more'),
    ]

    operations = [
    ]
