blank_issues_enabled: true
contact_links:
  - name: Matrix Chat
    url: https://matrix.to/#/#qgis-website:osgeo.org
    about: Our base of operations for group discussions on this project is our Matrix chat room
