# Generated by Django 4.2.13 on 2024-05-23 13:03

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_project_external_reviewer_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='accent_color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', help_text='A color represent the project color', image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
