# Generated by Django 4.2.20 on 2025-07-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_project_accent_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="certificate_credit",
        ),
        migrations.RemoveField(
            model_name="project",
            name="certification_managers",
        ),
        migrations.RemoveField(
            model_name="project",
            name="changelog_managers",
        ),
        migrations.RemoveField(
            model_name="project",
            name="credit_cost",
        ),
        migrations.RemoveField(
            model_name="project",
            name="credit_cost_currency",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_certification",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_changelogs",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_lessons",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_teams",
        ),
        migrations.RemoveField(
            model_name="project",
            name="lesson_managers",
        ),
        migrations.RemoveField(
            model_name="project",
            name="template_certifying_organisation_certificate",
        ),
    ]
