# Generated by Django 4.2.20 on 2025-07-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_remove_project_certificate_credit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="external_reviewer_invitation",
        ),
    ]
