name: Build and Push Docker Image on release
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Git tag to use'
  push:
    tags:
      - '*.*.*.'
      - 'v*.*.*.'
jobs:
  docker-builder-run-on-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deployment/docker/Dockerfile
          push: true
          target: prod
          tags: |
            qgis/qgis-members-uwsgi:${{ github.ref_name }}
            qgis/qgis-members-uwsgi:latest
      
      - name: Log out from Docker Hub
        run: docker logout

